[alembic]
# путь к файлу миграций
script_location = migrations

# шаблон для создания файлов миграций
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# в max_length_symbols символов будет обрезаться вывод представления при auto-generate
truncate_slug_length = 40

# DSN подключения к БД (будет переопределена программно)
sqlalchemy.url = postgresql+asyncpg://%(POSTGRES_USER)s:%(POSTGRES_PASSWORD)s@%(POSTGRES_HOST)s:%(POSTGRES_PORT)s/%(POSTGRES_DB)s

# использовать встроенную логику для именования ограничений
# удаления/добавления уникальных индексов
revision_environment = false

# Формат для вывода даты в сообщениях
# использует strftime директивы
file_date_format = %%Y-%%m-%%d %%H:%%M

# текстовая кодировка для ввода/вывода
# по умолчанию utf-8
# encoding = utf-8

# показывать использование БД движков коннектов при выводе
# verbose output
# output_encoding = utf-8

[post_write_hooks]
# post_write_hooks определяет скрипты или команды Python, запускаемые
# при успешном создании файлов ревизий.
# здесь пример хука, который форматирует Python-код с помощью black
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S