services:
  - type: web
    name: tg-bot-questionnaire
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: BOT_TOKEN
        sync: false  # Ручное заполнение через UI
      - key: DEBUG
        value: "True"
      # Автоматическое заполнение из базы данных
      - key: POSTGRES_DB
        fromDatabase:
          name: tg-bot-db
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: tg-bot-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: tg-bot-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: tg-bot-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: tg-bot-db
          property: password

databases:
  - name: tg-bot-db
    databaseName: quiz_bot
    user: postgres
    plan: free