services:
  # Telegram бот сервис через поллинг
  - type: web
    name: tg-bot-questionnaire
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_server.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: POSTGRES_USER
        fromDatabase:
          name: tg-bot-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: tg-bot-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: tg-bot-db
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: tg-bot-db
          property: host
      - key: POSTGRES_PORT
        value: "5432"
      - key: DEBUG
        value: "False"
      - key: PORT
        value: "10000"

databases:
  - name: tg-bot-db
    databaseName: quiz_bot
    user: postgres
    plan: free